language: python
branches:
  only:
    - master
    - /\bv[0-9]/
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[dev]
script:
  - pytest --cov=ipa
  - flake8 ipa
  - flake8 tests --exclude=data
deploy:
  provider: pypi
  user: "suse-pub-cloud-dev"
  password: $PYPI_PASS
  on:
    tags: true
  skip_existing: true
