language: python
branches:
  only:
    - master
    - /\bv[0-9]/
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -e .[dev]
script:
  - pytest --cov=ipa
  - flake8 ipa
  - flake8 tests --exclude=data
